### PR TITLE
ItemExtractor fix name resolution

### PR DESCRIPTION
**Pull request by stefanspiska**
closes https://github.com/ehrbase/openEHR_SDK/issues/98
and
closes https://github.com/ehrbase/fhir-bridge/issues/35

### CODE REVIEW

**Comment by SevKohler** [comment]
After rebuilding and rerunning everything, the error is the same unfortunately.

**Comment by stefanspiska** [comment]
It worked for me. Can you check  the code for ItemExtractor.java wich is included in the dependence corresponds to 
ItemExtractor.java

**Comment by SevKohler** [comment]
There was a bug in the fhir-bridge versioning number which was v.0.3.7 instead of 0.3.7 contained in the pom, that caused the error of not updating the openehrSDK within the bridge. Fixing this everything worked as intended.

**Review by SevKohler — COMMENTED** [review]
No complaints

**Pull request merged**
