### PR TITLE
Feature/372 ES openEHR terminology translation

### LINKED ISSUE #372: Add Spanish translation for the openEHR terminology
## Background ##

Compositions are not being validated correctly when some openEHR terminology codes have a value that is not in a supported language. For instance, if a composition is in Spanish, the compo.category.value will be "evento" and that returns a validation error since that term is not found associated with the openehr::433 code.

## Acceptance Criteria ##

Translate https://github.com/ehrbase/openEHR_SDK/tree/develop/terminology/src/main/resources

## Definition of Done ##

- [ ] Individual openEHR terminology file is in Spanish.

### PR DESCRIPTION
**Pull request by ppazos**
Closes #372

### CODE REVIEW

**Comment by birgerhaarbrandt** [comment]
@ppazos any suggestion how to review? May we ask Diego?

**Comment by ppazos** [comment]
@birgerhaarbrandt I will ask on discourse because I contributed the same file to the openEHR repo https://github.com/openEHR/terminology/pull/14

BTW while translating I detecting some errors in the original file https://github.com/openEHR/terminology/issues/12

**Comment by birgerhaarbrandt** [comment]
@ppazos did you receive sufficient feedback from the Spanish speaking part of the community?

**Comment by ppazos** [comment]
@birgerhaarbrandt I have added fixes based on the comments, there are a couple of terms in which there is a bit of controversy. Though I believe the current version is "good enough" and we can add the fixes later if needed.

**Pull request closed without merging**
