### PR TITLE
Use RmConstants and add missing rm type names

### PR DESCRIPTION
**Pull request by HolgerReiseVSys**

### CODE REVIEW

**Review by vmueller-vg — APPROVED** [review]
fine for this scope. I think i the future we could also introduce some constants for frequently used attribute names from the RM like "value", "name", etc

**Review by vmueller-vg — CHANGES_REQUESTED** [review]
Changelog entry is missing

**Comment by HolgerReiseVSys** [comment]
@vmueller-vg as this is just a minor refactoring, it seems there is nothing noteworthy

**Review by vmueller-vg — APPROVED** [review]
Fine

**Pull request merged**
