### PR TITLE
Added fix for Generator: Handle Norwegian characters #103

### PR DESCRIPTION
**Pull request by bjornna**
Fixed the issue #103  about Norwegian characters in field names. 

Note that this might be breaking change for clients with æøå in field names.

### CODE REVIEW

**Comment by birgerhaarbrandt** [comment]
@bjornna thanks a lot for the PR, much appreciated! There seems to be an issue on our side with Sonar Cloud, we will investigate what's happening.

**Comment by stefanspiska** [comment]
@birgerhaarbrandt 
As we profusely disused  about "ä"  there dos not seam to exist a java Library which translates language specific chars into there non special representation. 

I'm  very open to have, for the generator,  a externe configuration File where you can mange some generator options and one of this options could be language specific char replacements  table.

However I don't think that having  lots of methods like germanNormalize and norwegianNormalize si a scalable solution.

**Comment by bjornna** [comment]
I do agree. Will end up very confusing and messy. I was thinking about some extension mechanism where I could add my own normalizer. I.e run the generator with a set of such implemented interfaces.

I am using the generator from another Java application, and as such it would be easy and straight forward to add normalizer classes as part of the constructor or by some method.

**Comment by stefanspiska** [comment]
problem included in https://github.com/ehrbase/openEHR_SDK/pull/153

**Pull request closed without merging**
